output_data_type: "csv"
data_source_location: "./data/experiment_results.csv"
outputs_path: "./outputs"

data_connections:
  experiments:
    output_data_type: "csv"
    data_source_location: "./data/experiment_results.csv"
  measurements:
    output_data_type: "csv"
    data_source_location: "./data/measurements.csv"
